package org.cloudburstmc.protocol.bedrock.codec.v2168;

import org.cloudburstmc.protocol.bedrock.codec.BedrockCodec;
import org.cloudburstmc.protocol.bedrock.codec.EntityDataTypeMap;
import org.cloudburstmc.protocol.bedrock.codec.v1001.Bedrock_v1001;
import org.cloudburstmc.protocol.bedrock.codec.v1001.serializer.LevelSoundEventSerializer_v1001;
import org.cloudburstmc.protocol.bedrock.codec.v2168.serializer.*;
import org.cloudburstmc.protocol.bedrock.codec.v291.serializer.LevelEventSerializer_v291;
import org.cloudburstmc.protocol.bedrock.codec.v361.serializer.LevelEventGenericSerializer_v361;
import org.cloudburstmc.protocol.bedrock.data.LevelEventType;
import org.cloudburstmc.protocol.bedrock.data.MemoryCategoryCounter;
import org.cloudburstmc.protocol.bedrock.data.ParticleType;
import org.cloudburstmc.protocol.bedrock.data.SoundEvent;
import org.cloudburstmc.protocol.bedrock.data.entity.EntityDataFormat;
import org.cloudburstmc.protocol.bedrock.data.entity.EntityDataTypes;
import org.cloudburstmc.protocol.bedrock.data.entity.EntityFlag;
import org.cloudburstmc.protocol.bedrock.data.inventory.itemstack.request.action.ItemStackRequestActionType;
import org.cloudburstmc.protocol.bedrock.packet.*;
import org.cloudburstmc.protocol.bedrock.transformer.*;
import org.cloudburstmc.protocol.bedrock.util.TypeMap;

public class Bedrock_v2168 extends Bedrock_v1001 {

    protected static final TypeMap<MemoryCategoryCounter.Category> MEMORY_CATEGORY_TYPES = TypeMap.<MemoryCategoryCounter.Category>builder(MemoryCategoryCounter.Category.class)
            .insert(0, MemoryCategoryCounter.Category.UNKNOWN)
            .insert(1, MemoryCategoryCounter.Category.INVALID_SIZE_UNKNOWN)
            .insert(2, MemoryCategoryCounter.Category.ACTOR)
            .insert(3, MemoryCategoryCounter.Category.ACTOR_ANIMATION)
            .insert(4, MemoryCategoryCounter.Category.ACTOR_RENDERING)
            .insert(5, MemoryCategoryCounter.Category.BALANCER)
            .insert(6, MemoryCategoryCounter.Category.BLOCK_TICKING_QUEUES)
            .insert(7, MemoryCategoryCounter.Category.BIOME_STORAGE)
            .insert(8, MemoryCategoryCounter.Category.BLOBS)
            .insert(9, MemoryCategoryCounter.Category.CEREAL)
            .insert(10, MemoryCategoryCounter.Category.CIRCUIT_SYSTEM)
            .insert(11, MemoryCategoryCounter.Category.CLIENT)
            .insert(12, MemoryCategoryCounter.Category.COMMANDS)
            .insert(13, MemoryCategoryCounter.Category.DB_STORAGE)
            .insert(14, MemoryCategoryCounter.Category.DEBUG)
            .insert(15, MemoryCategoryCounter.Category.DOCUMENTATION)
            .insert(16, MemoryCategoryCounter.Category.ECS_SYSTEMS)
            .insert(17, MemoryCategoryCounter.Category.FMOD)
            .insert(18, MemoryCategoryCounter.Category.FONTS)
            .insert(19, MemoryCategoryCounter.Category.IM_GUI)
            .insert(20, MemoryCategoryCounter.Category.INPUT)
            .insert(21, MemoryCategoryCounter.Category.JSON_UI)
            .insert(22, MemoryCategoryCounter.Category.JSON_UI_CONTROL_FACTORY_JSON)
            .insert(23, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE)
            .insert(24, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_CONTROL_ELEMENT)
            .insert(25, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_DATA_BINDING)
            .insert(26, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_FOCUS)
            .insert(27, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_LAYOUT)
            .insert(28, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_OTHER)
            .insert(29, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_SPRITE)
            .insert(30, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_TEXT)
            .insert(31, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_TTS)
            .insert(32, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_VISIBILITY)
            .insert(33, MemoryCategoryCounter.Category.JSON_UI_CREATE_UI)
            .insert(34, MemoryCategoryCounter.Category.JSON_UI_DEFS)
            .insert(35, MemoryCategoryCounter.Category.JSON_UI_LAYOUT_MANAGER)
            .insert(36, MemoryCategoryCounter.Category.JSON_UI_LAYOUT_MANAGER_REMOVE_DEPENDENCIES)
            .insert(37, MemoryCategoryCounter.Category.JSON_UI_LAYOUT_MANAGER_INIT_VARIABLE)
            .insert(38, MemoryCategoryCounter.Category.LANGUAGES)
            .insert(39, MemoryCategoryCounter.Category.LEVEL)
            .insert(40, MemoryCategoryCounter.Category.LEVEL_STRUCTURES)
            .insert(41, MemoryCategoryCounter.Category.LEVEL_CHUNK)
            .insert(42, MemoryCategoryCounter.Category.LEVEL_CHUNK_GEN)
            .insert(43, MemoryCategoryCounter.Category.LEVEL_CHUNK_GEN_THREAD_LOCAL)
            .insert(44, MemoryCategoryCounter.Category.NETWORK)
            .insert(45, MemoryCategoryCounter.Category.MARKETPLACE)
            .insert(46, MemoryCategoryCounter.Category.MATERIAL_DRAGON_COMPILED_DEFINITION)
            .insert(47, MemoryCategoryCounter.Category.MATERIAL_DRAGON_MATERIAL)
            .insert(48, MemoryCategoryCounter.Category.MATERIAL_DRAGON_RESOURCE)
            .insert(49, MemoryCategoryCounter.Category.MATERIAL_DRAGON_UNIFORM_MAP)
            .insert(50, MemoryCategoryCounter.Category.MATERIAL_RENDER_MATERIAL)
            .insert(51, MemoryCategoryCounter.Category.MATERIAL_RENDER_MATERIAL_GROUP)
            .insert(52, MemoryCategoryCounter.Category.MATERIAL_VARIATION_MANAGER)
            .insert(53, MemoryCategoryCounter.Category.MOLANG)
            .insert(54, MemoryCategoryCounter.Category.ORE_UI)
            .insert(55, MemoryCategoryCounter.Category.ORE_UI_CLIENT)
            .insert(56, MemoryCategoryCounter.Category.PERSONA_PIECES)
            .insert(57, MemoryCategoryCounter.Category.PERSONA_ANIMATIONS)
            .insert(58, MemoryCategoryCounter.Category.PERSONA_TEXTURES)
            .insert(59, MemoryCategoryCounter.Category.PERSONA_CHARACTERS)
            .insert(60, MemoryCategoryCounter.Category.PERSONA_SKIN_PACKS)
            .insert(61, MemoryCategoryCounter.Category.PERSONA_REPO)
            .insert(62, MemoryCategoryCounter.Category.PLAYER)
            .insert(63, MemoryCategoryCounter.Category.RENDER_CHUNK)
            .insert(64, MemoryCategoryCounter.Category.RENDER_CHUNK_INDEX_BUFFER)
            .insert(65, MemoryCategoryCounter.Category.RENDER_CHUNK_VERTEX_BUFFER)
            .insert(66, MemoryCategoryCounter.Category.RENDERING)
            .insert(67, MemoryCategoryCounter.Category.RENDERING_BGFX_INIT)
            .insert(68, MemoryCategoryCounter.Category.RENDERING_BGFX_START_FRAME)
            .insert(69, MemoryCategoryCounter.Category.RENDERING_BLOCK_TESSELLATOR)
            .insert(70, MemoryCategoryCounter.Category.RENDERING_END_FRAME)
            .insert(71, MemoryCategoryCounter.Category.RENDERING_GRAPHICS_TASKS_INIT)
            .insert(72, MemoryCategoryCounter.Category.RENDERING_LIBRARY)
            .insert(73, MemoryCategoryCounter.Category.RENDERING_POLYGON_OPERATOR_POOL)
            .insert(74, MemoryCategoryCounter.Category.RENDERING_PBR_TEXTURE_DATA)
            .insert(75, MemoryCategoryCounter.Category.RENDERING_RENDER_REGISTRY)
            .insert(76, MemoryCategoryCounter.Category.RENDERING_SETUP)
            .insert(77, MemoryCategoryCounter.Category.RENDERING_VERTICES)
            .insert(78, MemoryCategoryCounter.Category.REQUEST_LOG)
            .insert(79, MemoryCategoryCounter.Category.RESOURCE_PACKS)
            .insert(80, MemoryCategoryCounter.Category.SOUND)
            .insert(81, MemoryCategoryCounter.Category.SUB_CHUNK_BIOME_DATA)
            .insert(82, MemoryCategoryCounter.Category.SUB_CHUNK_BLOCK_DATA)
            .insert(83, MemoryCategoryCounter.Category.SUB_CHUNK_LIGHT_DATA)
            .insert(84, MemoryCategoryCounter.Category.TEXTURES)
            .insert(85, MemoryCategoryCounter.Category.WEATHER_RENDERER)
            .insert(86, MemoryCategoryCounter.Category.WORLD_GENERATOR)
            .insert(87, MemoryCategoryCounter.Category.TASKS)
            .insert(88, MemoryCategoryCounter.Category.TEST)
            .insert(89, MemoryCategoryCounter.Category.TEST_LOAD_TEST_TAGS)
            .insert(90, MemoryCategoryCounter.Category.SCRIPTING)
            .insert(91, MemoryCategoryCounter.Category.SCRIPTING_RUNTIME)
            .insert(92, MemoryCategoryCounter.Category.SCRIPTING_CONTEXT)
            .insert(93, MemoryCategoryCounter.Category.SCRIPTING_CONTEXT_BINDINGS_MC)
            .insert(94, MemoryCategoryCounter.Category.SCRIPTING_CONTEXT_BINDINGS_GT)
            .insert(95, MemoryCategoryCounter.Category.SCRIPTING_CONTEXT_RUN)
            .insert(96, MemoryCategoryCounter.Category.DATA_DRIVEN_UI)
            .insert(97, MemoryCategoryCounter.Category.DATA_DRIVEN_UI_DEFS)
            .insert(98, MemoryCategoryCounter.Category.GAMEFACE)
            .insert(99, MemoryCategoryCounter.Category.GAMEFACE_SYSTEM)
            .insert(100, MemoryCategoryCounter.Category.GAMEFACE_DOM)
            .insert(101, MemoryCategoryCounter.Category.GAMEFACE_CSS)
            .insert(102, MemoryCategoryCounter.Category.GAMEFACE_DISPLAY)
            .insert(103, MemoryCategoryCounter.Category.GAMEFACE_TEMP_ALLOCATOR)
            .insert(104, MemoryCategoryCounter.Category.GAMEFACE_POOL_ALLOCATOR)
            .insert(105, MemoryCategoryCounter.Category.GAMEFACE_DUMP)
            .insert(106, MemoryCategoryCounter.Category.GAMEFACE_MEDIA)
            .insert(107, MemoryCategoryCounter.Category.GAMEFACE_JSON)
            .insert(108, MemoryCategoryCounter.Category.GAMEFACE_SCRIPT_ENGINE)
            .insert(109, MemoryCategoryCounter.Category.GAMEFACE_SCRIPT)
            .insert(110, MemoryCategoryCounter.Category.GAMEFACE_LAYOUT)
            .insert(111, MemoryCategoryCounter.Category.VR)
            .build();

    protected static final TypeMap<EntityFlag> ENTITY_FLAGS = Bedrock_v1001.ENTITY_FLAGS
            .toBuilder()
            .insert(130, EntityFlag.NOT_PICKABLE_FROM_INSIDE)
            .build();

    protected static final TypeMap<ParticleType> PARTICLE_TYPES = Bedrock_v1001.PARTICLE_TYPES.toBuilder()
            .insert(102, ParticleType.ORANGE_POPLAR_LEAVES)
            .insert(103, ParticleType.RED_POPLAR_LEAVES)
            .insert(104, ParticleType.YELLOW_POPLAR_LEAVES)
            .build();

    protected static final EntityDataTypeMap ENTITY_DATA = Bedrock_v1001.ENTITY_DATA
            .toBuilder()
            .update(EntityDataTypes.AREA_EFFECT_CLOUD_PARTICLE, new TypeMapTransformer<>(PARTICLE_TYPES))
            .update(EntityDataTypes.FLAGS, new FlagTransformer(ENTITY_FLAGS, 0))
            .update(EntityDataTypes.FLAGS_2, new FlagTransformer(ENTITY_FLAGS, 1))
            .remove(16)
            .insert(EntityDataTypes.DISPLAY_BLOCK_STATE, 16, EntityDataFormat.INT, new BlockDefinitionTransformer())
            .insert(EntityDataTypes.DISPLAY_FIREWORK, 16, EntityDataFormat.NBT)
            .insert(EntityDataTypes.HORSE_FLAGS, 16, EntityDataFormat.LONG, Long2IntTransformer.INSTANCE)
            .insert(EntityDataTypes.WITHER_SKULL_DANGEROUS, 16, EntityDataFormat.BYTE)
            .insert(EntityDataTypes.UNKNOWN_HORSE_INT_25, 25, EntityDataFormat.INT)
            .build();

    protected static final TypeMap<LevelEventType> LEVEL_EVENTS = Bedrock_v1001.LEVEL_EVENTS.toBuilder()
            .insert(LEVEL_EVENT_PARTICLE_TYPE, PARTICLE_TYPES)
            .build();

    protected static final TypeMap<ItemStackRequestActionType> ITEM_STACK_REQUEST_TYPES = TypeMap.builder(ItemStackRequestActionType.class)
            .insert(0, ItemStackRequestActionType.TAKE)
            .insert(1, ItemStackRequestActionType.PLACE)
            .insert(2, ItemStackRequestActionType.SWAP)
            .insert(3, ItemStackRequestActionType.DROP)
            .insert(4, ItemStackRequestActionType.DESTROY)
            .insert(5, ItemStackRequestActionType.CONSUME)
            .insert(6, ItemStackRequestActionType.CREATE)
            .insert(7, ItemStackRequestActionType.LAB_TABLE_COMBINE)
            .insert(8, ItemStackRequestActionType.BEACON_PAYMENT)
            .insert(9, ItemStackRequestActionType.MINE_BLOCK)
            .insert(10, ItemStackRequestActionType.CRAFT_RECIPE)
            .insert(11, ItemStackRequestActionType.CRAFT_RECIPE_AUTO)
            .insert(12, ItemStackRequestActionType.CRAFT_CREATIVE)
            .insert(13, ItemStackRequestActionType.CRAFT_RECIPE_OPTIONAL)
            .insert(14, ItemStackRequestActionType.CRAFT_REPAIR_AND_DISENCHANT)
            .insert(15, ItemStackRequestActionType.CRAFT_LOOM)
            .insert(16, ItemStackRequestActionType.CRAFT_NON_IMPLEMENTED_DEPRECATED)
            .insert(17, ItemStackRequestActionType.CRAFT_RESULTS_DEPRECATED)
            .build();

    protected static final TypeMap<SoundEvent> SOUND_EVENTS = Bedrock_v1001.SOUND_EVENTS
            .toBuilder()
            .replace(611, SoundEvent.MOUNT)
            .insert(612, SoundEvent.DISMOUNT)
            .insert(613, SoundEvent.STRAW_BED_BREAK_LEAVE)
            .insert(614, SoundEvent.UNDEFINED)
            .build();

    public static final BedrockCodec CODEC = Bedrock_v1001.CODEC.toBuilder()
            .protocolVersion(2168)
            .minecraftVersion("1.26.40")
            .helper(() -> new BedrockCodecHelper_v2168(ENTITY_DATA, GAME_RULE_TYPES, ITEM_STACK_REQUEST_TYPES, CONTAINER_SLOT_TYPES, PLAYER_ABILITIES, TEXT_PROCESSING_ORIGINS))
            .updateSerializer(AnvilDamagePacket.class, AnvilDamageSerializer_v2168.INSTANCE)
            .updateSerializer(ClientboundMapItemDataPacket.class, ClientboundMapItemDataSerializer_v2168.INSTANCE)
            .updateSerializer(ClientboundUpdateSoundDataPacket.class, ClientboundUpdateSoundDataSerializer_v2168.INSTANCE)
            .updateSerializer(CraftingDataPacket.class, CraftingDataSerializer_v2168.INSTANCE)
            .updateSerializer(CreativeContentPacket.class, CreativeContentSerializer_v2168.INSTANCE)
            .updateSerializer(DimensionDataPacket.class, DimensionDataSerializer_v2168.INSTANCE)
            .updateSerializer(ItemStackResponsePacket.class, ItemStackResponseSerializer_v2168.INSTANCE)
            .updateSerializer(LevelChunkPacket.class, LevelChunkSerializer_v2168.INSTANCE)
            .updateSerializer(LevelEventPacket.class, new LevelEventSerializer_v291(LEVEL_EVENTS))
            .updateSerializer(LevelEventGenericPacket.class, new LevelEventGenericSerializer_v361(LEVEL_EVENTS))
            .updateSerializer(LevelSoundEventPacket.class, new LevelSoundEventSerializer_v1001(SOUND_EVENTS))
            .updateSerializer(MoveEntityDeltaPacket.class, MoveEntityDeltaSerializer_v2168.INSTANCE)
            .updateSerializer(MovePlayerPacket.class, MovePlayerSerializer_v2168.INSTANCE)
            .updateSerializer(PlayerAuthInputPacket.class, PlayerAuthInputSerializer_v2168.INSTANCE)
            .updateSerializer(PlayerListPacket.class, PlayerListSerializer_v2168.INSTANCE)
            .updateSerializer(PlayerLocationPacket.class, PlayerLocationSerializer_v2168.INSTANCE)
            .updateSerializer(PlayerSkinPacket.class, PlayerSkinSerializer_v2168.INSTANCE)
            .updateSerializer(PlayerUpdateEntityOverridesPacket.class, PlayerUpdateEntityOverridesSerializer_v2168.INSTANCE)
            .updateSerializer(PlaySoundPacket.class, PlaySoundSerializer_v2168.INSTANCE)
            .updateSerializer(ResourcePackClientResponsePacket.class, ResourcePackClientResponseSerializer_v2168.INSTANCE)
            .updateSerializer(ResourcePacksInfoPacket.class, ResourcePacksInfoSerializer_v2168.INSTANCE)
            .updateSerializer(SetScorePacket.class, SetScoreSerializer_v2168.INSTANCE)
            .updateSerializer(SetScoreboardIdentityPacket.class, SetScoreboardIdentitySerializer_v2168.INSTANCE)
            .updateSerializer(ServerboundDiagnosticsPacket.class, new ServerboundDiagnosticsSerializer_v2168(MEMORY_CATEGORY_TYPES))
            .updateSerializer(StartGamePacket.class, StartGameSerializer_v2168.INSTANCE)
            .updateSerializer(StructureBlockUpdatePacket.class, StructureBlockUpdateSerializer_v2168.INSTANCE)
            .updateSerializer(SubChunkPacket.class, SubChunkSerializer_v2168.INSTANCE)
            .updateSerializer(TransferPacket.class, TransferSerializer_v2168.INSTANCE)
            .build();
}
