package org.cloudburstmc.protocol.bedrock.codec.v2193;

import org.cloudburstmc.protocol.bedrock.codec.BedrockCodec;
import org.cloudburstmc.protocol.bedrock.codec.v2168.Bedrock_v2168;
import org.cloudburstmc.protocol.bedrock.codec.v2169.Bedrock_v2169;
import org.cloudburstmc.protocol.bedrock.codec.v2193.serializer.*;
import org.cloudburstmc.protocol.bedrock.data.PacketRecipient;
import org.cloudburstmc.protocol.bedrock.data.MemoryCategoryCounter;
import org.cloudburstmc.protocol.bedrock.util.TypeMap;
import org.cloudburstmc.protocol.bedrock.packet.*;

public final class Bedrock_v2193 extends Bedrock_v2168 {

    protected static final TypeMap<MemoryCategoryCounter.Category> MEMORY_CATEGORY_TYPES_2193 =
            TypeMap.builder(MemoryCategoryCounter.Category.class)
            .insert(0, MemoryCategoryCounter.Category.UNKNOWN)
            .insert(1, MemoryCategoryCounter.Category.INVALID_SIZE_UNKNOWN)
            .insert(2, MemoryCategoryCounter.Category.ACTOR)
            .insert(3, MemoryCategoryCounter.Category.ACTOR_ANIMATION)
            .insert(4, MemoryCategoryCounter.Category.ACTOR_RENDERING)
            .insert(5, MemoryCategoryCounter.Category.BLOCK_TICKING_QUEUES)
            .insert(6, MemoryCategoryCounter.Category.BIOME_STORAGE)
            .insert(7, MemoryCategoryCounter.Category.BLOBS)
            .insert(8, MemoryCategoryCounter.Category.CEREAL)
            .insert(9, MemoryCategoryCounter.Category.CIRCUIT_SYSTEM)
            .insert(10, MemoryCategoryCounter.Category.CLIENT)
            .insert(11, MemoryCategoryCounter.Category.COMMANDS)
            .insert(12, MemoryCategoryCounter.Category.DB_STORAGE)
            .insert(13, MemoryCategoryCounter.Category.DEBUG)
            .insert(14, MemoryCategoryCounter.Category.DOCUMENTATION)
            .insert(15, MemoryCategoryCounter.Category.ECS_SYSTEMS)
            .insert(16, MemoryCategoryCounter.Category.FMOD)
            .insert(17, MemoryCategoryCounter.Category.FONTS)
            .insert(18, MemoryCategoryCounter.Category.IM_GUI)
            .insert(19, MemoryCategoryCounter.Category.INPUT)
            .insert(20, MemoryCategoryCounter.Category.JSON_UI)
            .insert(21, MemoryCategoryCounter.Category.JSON_UI_CONTROL_FACTORY_JSON)
            .insert(22, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE)
            .insert(23, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_CONTROL_ELEMENT)
            .insert(24, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_DATA_BINDING)
            .insert(25, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_FOCUS)
            .insert(26, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_LAYOUT)
            .insert(27, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_OTHER)
            .insert(28, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_SPRITE)
            .insert(29, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_TEXT)
            .insert(30, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_POPULATE_TTS)
            .insert(31, MemoryCategoryCounter.Category.JSON_UI_CONTROL_TREE_VISIBILITY)
            .insert(32, MemoryCategoryCounter.Category.JSON_UI_CREATE_UI)
            .insert(33, MemoryCategoryCounter.Category.JSON_UI_DEFS)
            .insert(34, MemoryCategoryCounter.Category.JSON_UI_LAYOUT_MANAGER)
            .insert(35, MemoryCategoryCounter.Category.JSON_UI_LAYOUT_MANAGER_REMOVE_DEPENDENCIES)
            .insert(36, MemoryCategoryCounter.Category.JSON_UI_LAYOUT_MANAGER_INIT_VARIABLE)
            .insert(37, MemoryCategoryCounter.Category.LANGUAGES)
            .insert(38, MemoryCategoryCounter.Category.LEVEL)
            .insert(39, MemoryCategoryCounter.Category.LEVEL_STRUCTURES)
            .insert(40, MemoryCategoryCounter.Category.LEVEL_CHUNK)
            .insert(41, MemoryCategoryCounter.Category.LEVEL_CHUNK_GEN)
            .insert(42, MemoryCategoryCounter.Category.LEVEL_CHUNK_GEN_THREAD_LOCAL)
            .insert(43, MemoryCategoryCounter.Category.LIGHT_VOLUME_MANAGER)
            .insert(44, MemoryCategoryCounter.Category.NETWORK)
            .insert(45, MemoryCategoryCounter.Category.MARKETPLACE)
            .insert(46, MemoryCategoryCounter.Category.MATERIAL_DRAGON_COMPILED_DEFINITION)
            .insert(47, MemoryCategoryCounter.Category.MATERIAL_DRAGON_MATERIAL)
            .insert(48, MemoryCategoryCounter.Category.MATERIAL_DRAGON_RESOURCE)
            .insert(49, MemoryCategoryCounter.Category.MATERIAL_DRAGON_UNIFORM_MAP)
            .insert(50, MemoryCategoryCounter.Category.MATERIAL_RENDER_MATERIAL)
            .insert(51, MemoryCategoryCounter.Category.MATERIAL_RENDER_MATERIAL_GROUP)
            .insert(52, MemoryCategoryCounter.Category.MATERIAL_VARIATION_MANAGER)
            .insert(53, MemoryCategoryCounter.Category.MOLANG)
            .insert(54, MemoryCategoryCounter.Category.ORE_UI)
            .insert(55, MemoryCategoryCounter.Category.ORE_UI_CLIENT)
            .insert(56, MemoryCategoryCounter.Category.PERSONA_PIECES)
            .insert(57, MemoryCategoryCounter.Category.PERSONA_ANIMATIONS)
            .insert(58, MemoryCategoryCounter.Category.PERSONA_CHARACTERS)
            .insert(59, MemoryCategoryCounter.Category.PERSONA_SKIN_PACKS)
            .insert(60, MemoryCategoryCounter.Category.PERSONA_REPO)
            .insert(61, MemoryCategoryCounter.Category.PLAYER)
            .insert(62, MemoryCategoryCounter.Category.RENDER_CHUNK)
            .insert(63, MemoryCategoryCounter.Category.RENDER_CHUNK_INDEX_BUFFER)
            .insert(64, MemoryCategoryCounter.Category.RENDER_CHUNK_VERTEX_BUFFER)
            .insert(65, MemoryCategoryCounter.Category.RENDERING)
            .insert(66, MemoryCategoryCounter.Category.RENDERING_BGFX_INIT)
            .insert(67, MemoryCategoryCounter.Category.RENDERING_BGFX_START_FRAME)
            .insert(68, MemoryCategoryCounter.Category.RENDERING_BLOCK_TESSELLATOR)
            .insert(69, MemoryCategoryCounter.Category.RENDERING_END_FRAME)
            .insert(70, MemoryCategoryCounter.Category.RENDERING_GRAPHICS_TASKS_INIT)
            .insert(71, MemoryCategoryCounter.Category.RENDERING_LIBRARY)
            .insert(72, MemoryCategoryCounter.Category.RENDERING_POLYGON_OPERATOR_POOL)
            .insert(73, MemoryCategoryCounter.Category.RENDERING_PBR_TEXTURE_DATA)
            .insert(74, MemoryCategoryCounter.Category.RENDERING_RENDER_REGISTRY)
            .insert(75, MemoryCategoryCounter.Category.RENDERING_SETUP)
            .insert(76, MemoryCategoryCounter.Category.RENDERING_VERTICES)
            .insert(77, MemoryCategoryCounter.Category.REQUEST_LOG)
            .insert(78, MemoryCategoryCounter.Category.RESOURCE_PACKS)
            .insert(79, MemoryCategoryCounter.Category.SOUND)
            .insert(80, MemoryCategoryCounter.Category.SUB_CHUNK_BIOME_DATA)
            .insert(81, MemoryCategoryCounter.Category.SUB_CHUNK_BLOCK_DATA)
            .insert(82, MemoryCategoryCounter.Category.SUB_CHUNK_LIGHT_DATA)
            .insert(83, MemoryCategoryCounter.Category.TEXTURES)
            .insert(84, MemoryCategoryCounter.Category.WEATHER_RENDERER)
            .insert(85, MemoryCategoryCounter.Category.WORLD_GENERATOR)
            .insert(86, MemoryCategoryCounter.Category.TASKS)
            .insert(87, MemoryCategoryCounter.Category.TEST)
            .insert(88, MemoryCategoryCounter.Category.TEST_LOAD_TEST_TAGS)
            .insert(89, MemoryCategoryCounter.Category.SCRIPTING)
            .insert(90, MemoryCategoryCounter.Category.SCRIPTING_RUNTIME)
            .insert(91, MemoryCategoryCounter.Category.SCRIPTING_CONTEXT)
            .insert(92, MemoryCategoryCounter.Category.SCRIPTING_CONTEXT_BINDINGS_MC)
            .insert(93, MemoryCategoryCounter.Category.SCRIPTING_CONTEXT_BINDINGS_GT)
            .insert(94, MemoryCategoryCounter.Category.SCRIPTING_CONTEXT_RUN)
            .insert(95, MemoryCategoryCounter.Category.DATA_DRIVEN_UI)
            .insert(96, MemoryCategoryCounter.Category.DATA_DRIVEN_UI_DEFS)
            .insert(97, MemoryCategoryCounter.Category.GAMEFACE)
            .insert(98, MemoryCategoryCounter.Category.GAMEFACE_SYSTEM)
            .insert(99, MemoryCategoryCounter.Category.GAMEFACE_DOM)
            .insert(100, MemoryCategoryCounter.Category.GAMEFACE_CSS)
            .insert(101, MemoryCategoryCounter.Category.GAMEFACE_DISPLAY)
            .insert(102, MemoryCategoryCounter.Category.GAMEFACE_TEMP_ALLOCATOR)
            .insert(103, MemoryCategoryCounter.Category.GAMEFACE_POOL_ALLOCATOR)
            .insert(104, MemoryCategoryCounter.Category.GAMEFACE_DUMP)
            .insert(105, MemoryCategoryCounter.Category.GAMEFACE_MEDIA)
            .insert(106, MemoryCategoryCounter.Category.GAMEFACE_JSON)
            .insert(107, MemoryCategoryCounter.Category.GAMEFACE_SCRIPT_ENGINE)
            .insert(108, MemoryCategoryCounter.Category.GAMEFACE_SCRIPT)
            .insert(109, MemoryCategoryCounter.Category.GAMEFACE_LAYOUT)
            .build();

    public static final BedrockCodec CODEC = Bedrock_v2169.CODEC.toBuilder()
            .protocolVersion(2193)
            .minecraftVersion("1.26.52")
            .helper(() -> new BedrockCodecHelper_v2193(
                    ENTITY_DATA,
                    GAME_RULE_TYPES,
                    ITEM_STACK_REQUEST_TYPES,
                    CONTAINER_SLOT_TYPES,
                    PLAYER_ABILITIES,
                    TEXT_PROCESSING_ORIGINS
            ))
            .updateSerializer(BossEventPacket.class, BossEventSerializer_v2193.INSTANCE)
            .updateSerializer(CameraPresetsPacket.class, CameraPresetsSerializer_v2193.INSTANCE)
            .updateSerializer(ClientboundAttributeLayerSyncPacket.class, ClientboundAttributeLayerSyncSerializer_v2193.INSTANCE)
            .updateSerializer(PrimitiveShapesPacket.class, PrimitiveShapesSerializer_v2193.INSTANCE)
            .updateSerializer(DimensionDataPacket.class, DimensionDataSerializer_v2193.INSTANCE)
            .updateSerializer(InventoryTransactionPacket.class, InventoryTransactionSerializer_v2193.INSTANCE)
            .updateSerializer(ItemStackResponsePacket.class, ItemStackResponseSerializer_v2193.INSTANCE)
            .updateSerializer(MoveEntityDeltaPacket.class, MoveEntityDeltaSerializer_v2193.INSTANCE)
            .updateSerializer(PlayerAuthInputPacket.class, PlayerAuthInputSerializer_v2193.INSTANCE)
            .updateSerializer(PlaySoundPacket.class, PlaySoundSerializer_v2193.INSTANCE)
            .updateSerializer(SubChunkPacket.class, SubChunkSerializer_v2193.INSTANCE)
            .updateSerializer(ServerboundDiagnosticsPacket.class,
                    new ServerboundDiagnosticsSerializer_v2193(MEMORY_CATEGORY_TYPES_2193))
            .updateSerializer(ServerboundPackSettingChangePacket.class, ServerboundPackSettingChangeSerializer_v2193.INSTANCE)
            .registerPacket(SetPlayerFurnaceOptionsPacket::new, SetPlayerFurnaceOptionsSerializer_v2193.INSTANCE, 351, PacketRecipient.BOTH)
            .registerPacket(RecordStartedPacket::new, RecordStartedSerializer_v2193.INSTANCE, 352, PacketRecipient.CLIENT)
            .build();

    private Bedrock_v2193() {
    }
}
